name: mosaiks-env
channels:
  - pytorch
  - conda-forge
  - r
  - bolliger32
dependencies:
# only needed for interactivity
  - black=20.8b1=py_1
  - isort=5.8.0=pyhd8ed1ab_0
  - jupyterlab=3.0.14=pyhd8ed1ab_0
  - jupyterlab_code_formatter=1.4.10=pyhd8ed1ab_1
  - jupyter-resource-usage=0.5.1=pyhd8ed1ab_0
  - nodejs=15.14.0
# needed for core functionality of package
  - blas=2.108=mkl
  - cartopy=0.18.0
  - cudatoolkit
  - dill=0.3.3
  - dask=2021.2.0
  - distributed=2021.2.0
  - geopandas=0.9.0
  - imageio=2.9.0
  - loguru=0.5.3
  - matplotlib=3.4.1
  - numba=0.53.1
  - numpy=1.20.2
  - pandas=1.2.4
  - papermill=2.3.3
  - phantomjs=2.1.1
  - pip=21.0.1
  - python=3.9.2
  - pytorch=1.8.1
  - redis-py=3.5.3
  - scikit-image=0.18.1
  - scikit-learn=0.24.1
  - seaborn=0.11.1
  - shapely=1.7.1
  - tensorboardx=2.2
  - torchvision=0.2.2
  - tqdm=4.60.0
  - xarray=0.17.0
  - r-acs=2.1.4
  - r-cowplot=1.1.1
  - r-doparallel=1.0.16
  - r-elevatr=0.1.4
  - r-emdbook=1.3.12
  - r-essentials=3.6
  - r-ggextra=0.9
  - r-here=1.0.1
  - r-kableextra=1.3.4
  - r-lwgeom=0.2_5
  - r-magick=2.7.1
  - r-mapdata=2.3.0
  - r-maptools=1.1_1
  - r-ncdf4=1.17
  - r-png=0.1_7
  - r-raster=3.4_5
  - r-rcppcnpy=0.2.10
  - r-reticulate=1.18
  - r-rgdal=1.5_16
  - r-rgeos=0.5_5
  - r-sf=0.9_7
  - r-usaboundaries=0.3.1
